# Generated by Django 6.0.7 on 2026-09-05 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='branch',
            field=models.CharField(blank=True, default='COMMON', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='course',
            field=models.CharField(blank=True, default='B.Tech', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='semester',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='year',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, default='CSE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, default='B.Tech Computer Science & Engineering', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.CreateModel(
            name='StudentAttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Excused', 'Excused')], default='Present', max_length=20)),
                ('topic', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab', models.ForeignKey(db_column='lab_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='api.lab')),
                ('student', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_attendance_sessions',
            },
        ),
    ]
