# Generated by Django 6.0.7 on 2026-09-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lab_branch_lab_course_lab_semester_lab_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentsubmission',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
