# Generated by Django 6.0.7 on 2026-09-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_studentsubmission_feedback_studentsubmission_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('user_id', models.CharField(max_length=50)),
                ('password_hash', models.TextField()),
                ('dept', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, default='B.Tech Computer Science & Engineering', max_length=100, null=True)),
                ('branch', models.CharField(blank=True, default='CSE', max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, default=1, null=True)),
                ('semester', models.IntegerField(blank=True, default=1, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_registration_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
