import os
import datetime
import re
from django.core.management.base import BaseCommand
from django.contrib.auth.hashers import make_password
from api.models import (
    User,
    Lab,
    EquipmentStatus,
    LabModule,
    TeacherBatch,
    Task,
    StudentRecord,
    StudentSubmission,
    LabAttendance,
    Grade,
    StudentAttendanceSession,
    EquipmentAssignment,
    LiveWorkbench,
)

class Command(BaseCommand):
    help = 'Seeds initial database for Lab Companion with real-time B.Tech student dataset and real calendar lab details'

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.NOTICE('Beginning database seeding with real-time dataset across 10 B.Tech branches...'))

        # 1. Clear all old demo records
        StudentAttendanceSession.objects.all().delete()
        Grade.objects.all().delete()
        LabAttendance.objects.all().delete()
        StudentSubmission.objects.all().delete()
        StudentRecord.objects.all().delete()
        Task.objects.all().delete()
        TeacherBatch.objects.all().delete()
        LabModule.objects.all().delete()
        EquipmentStatus.objects.all().delete()
        Lab.objects.all().delete()
        User.objects.all().delete()
        EquipmentAssignment.objects.all().delete()
        LiveWorkbench.objects.all().delete()

        # 2. Table: users - Sole Institutional Administrator
        admin_email = os.environ.get('ADMIN_EMAIL', 'admin@gmail.com')
        admin_pass = os.environ.get('ADMIN_PASSWORD', 'admin123')
        admin_user = User.objects.create(
            email=admin_email,
            password=make_password(admin_pass),
            role='admin',
            user_id='admin',
            name='Institutional Admin',
            dept='Central Engineering Facilities & Administration',
            course='Faculty Administration',
            branch='ADMIN',
            year=None,
            semester=None,
            phone='+91 98000 00101',
        )
        self.stdout.write(self.style.SUCCESS(f"Created administrator account 'admin' ({admin_email})."))

        # 3. Table: labs (Real Date & Time Schedules, B.Tech Curriculum Aligned)
        labs_data = [
            # Semester 1
            {
                'lab_code': 'LAB-101',
                'name': 'Problem Solving & C Programming Lab',
                'credits': 2,
                'course': 'B.Tech',
                'branch': 'COMMON',
                'year': 1,
                'semester': 1,
                'day': 'Monday',
                'time_slot': '09:00 AM - 12:00 PM',
                'room': 'Computing Block - Lab 102',
                'teacher_name': 'Prof. Marcus Vance',
                'attendance': '95%',
                'grade': 'A',
                'equipment': 'Linux Workstations, GCC 14.2 compiler suite, GDB debuggers',
                'latest_update': 'Pointers and dynamic memory allocation worksheets updated.',
            },
            {
                'lab_code': 'LAB-102',
                'name': 'Basic Electrical & Electronics Engineering Lab',
                'credits': 2,
                'course': 'B.Tech',
                'branch': 'COMMON',
                'year': 1,
                'semester': 1,
                'day': 'Tuesday',
                'time_slot': '01:30 PM - 04:30 PM',
                'room': 'Electrical Annex - Bay 04',
                'teacher_name': 'Dr. Aman Gupta',
                'attendance': '92%',
                'grade': 'A-',
                'equipment': 'Dual-channel DC power supplies, Digital multimeters, Function generators',
                'latest_update': 'Verification of Thevenin and Norton theorems calibrated.',
            },
            # Semester 2
            {
                'lab_code': 'LAB-201',
                'name': 'Python Programming & Computational Thinking Lab',
                'credits': 2,
                'course': 'B.Tech',
                'branch': 'COMMON',
                'year': 1,
                'semester': 2,
                'day': 'Monday',
                'time_slot': '01:30 PM - 04:30 PM',
                'room': 'Computing Block - Lab 104',
                'teacher_name': 'Prof. Marcus Vance',
                'attendance': '96%',
                'grade': 'A+',
                'equipment': 'Python 3.13 nodes, NumPy, Pandas, Matplotlib environments',
                'latest_update': 'NumPy matrix manipulation benchmark problem sets released.',
            },
            {
                'lab_code': 'LAB-204',
                'name': 'Surveying & Geomatics Lab',
                'credits': 2,
                'course': 'B.Tech',
                'branch': 'CIVIL',
                'year': 1,
                'semester': 2,
                'day': 'Thursday',
                'time_slot': '09:30 AM - 12:30 PM',
                'room': 'Civil Geomatics Field Station',
                'teacher_name': 'Prof. R. C. Chatterjee',
                'attendance': '90%',
                'grade': 'B+',
                'equipment': 'Total Stations, Auto Levels, Theodolites, GPS Survey Handhelds',
                'latest_update': 'Contour leveling and triangulation benchmarks surveyed.',
            },
            {
                'lab_code': 'LAB-261',
                'name': 'Robotics Kinematics & Sensors Lab',
                'credits': 2,
                'course': 'B.Tech',
                'branch': 'RA',
                'year': 1,
                'semester': 2,
                'day': 'Friday',
                'time_slot': '10:00 AM - 01:00 PM',
                'room': 'Mechatronics Wing - Rig 01',
                'teacher_name': 'Dr. K. Srinivas',
                'attendance': '91%',
                'grade': 'A-',
                'equipment': '6-DOF Robotic Manipulators, Ultrasonic & LIDAR sensor rigs, Arduino/ESP32 testbeds',
                'latest_update': 'Inverse kinematics and PID closed-loop trajectory calibration completed.',
            },
            # Semester 3
            {
                'lab_code': 'LAB-301',
                'name': 'Data Structures & Algorithms (C++/Java) Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'CSE',
                'year': 2,
                'semester': 3,
                'day': 'Monday',
                'time_slot': '09:00 AM - 11:30 AM',
                'room': 'Computing Systems Lab 204',
                'teacher_name': 'Prof. Marcus Vance',
                'attendance': '98%',
                'grade': 'A+',
                'equipment': 'Linux C++23 terminals, Valgrind profilers, Clang sanitizers',
                'latest_update': 'AVL tree and Graph Dijkstra benchmark problem sets released.',
            },
            {
                'lab_code': 'LAB-302',
                'name': 'Object Oriented Programming with Java Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'CSE',
                'year': 2,
                'semester': 3,
                'day': 'Monday',
                'time_slot': '01:15 PM - 03:15 PM',
                'room': 'Software Towers - Lab 302',
                'teacher_name': 'Prof. Marcus Vance',
                'attendance': '95%',
                'grade': 'A',
                'equipment': 'OpenJDK 21 LTS, IntelliJ IDEA, JUnit 5 test harness',
                'latest_update': 'Multithreading and thread synchronization assignment live.',
            },
            {
                'lab_code': 'LAB-303',
                'name': 'Digital Electronics & Verilog HDL Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'ECE',
                'year': 2,
                'semester': 3,
                'day': 'Tuesday',
                'time_slot': '09:00 AM - 11:30 AM',
                'room': 'VLSI & Embedded Lab 202',
                'teacher_name': 'Dr. Aman Gupta',
                'attendance': '94%',
                'grade': 'A',
                'equipment': 'Xilinx Vivado 2026, Basys 3 FPGA boards, Mixed-signal oscilloscopes',
                'latest_update': '16-bit ALU and Finite State Machine synthesis verified.',
            },
            {
                'lab_code': 'LAB-311',
                'name': 'Electronic Devices & Circuits (EDC) Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'ECE',
                'year': 2,
                'semester': 3,
                'day': 'Tuesday',
                'time_slot': '02:00 PM - 04:30 PM',
                'room': 'Microelectronics Wing - Lab 108',
                'teacher_name': 'Dr. Sarah Jenkins',
                'attendance': '93%',
                'grade': 'A-',
                'equipment': 'Keysight 100MHz scopes, NI ELVIS III stations, BJT/MOSFET testbenches',
                'latest_update': 'Common-emitter amplifier frequency response calibrated.',
            },
            {
                'lab_code': 'LAB-351',
                'name': 'Microprocessors & Interfacing (8086/ARM) Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'ECM',
                'year': 2,
                'semester': 3,
                'day': 'Wednesday',
                'time_slot': '10:00 AM - 01:00 PM',
                'room': 'Embedded Systems Bay 305',
                'teacher_name': 'Prof. N. K. Deshmukh',
                'attendance': '92%',
                'grade': 'A-',
                'equipment': 'ARM Cortex-M4 boards, Keil MicroVision, 8086 trainer kits',
                'latest_update': 'DAC waveform generation and 8255 PPI interfacing experiments tested.',
            },
            # Semester 4
            {
                'lab_code': 'LAB-401',
                'name': 'Operating Systems & Linux Kernel Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'CSE',
                'year': 2,
                'semester': 4,
                'day': 'Monday',
                'time_slot': '01:30 PM - 04:30 PM',
                'room': 'Computing Systems Lab 206',
                'teacher_name': 'Prof. Marcus Vance',
                'attendance': '97%',
                'grade': 'A+',
                'equipment': 'QEMU virtual machine clusters, Linux kernel 6.8 build nodes',
                'latest_update': 'System calls, semaphore IPC, and virtual memory page replacement simulated.',
            },
            {
                'lab_code': 'LAB-402',
                'name': 'Database Management Systems (SQL) Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'CSE',
                'year': 2,
                'semester': 4,
                'day': 'Wednesday',
                'time_slot': '10:00 AM - 12:00 PM',
                'room': 'Database Bay 401',
                'teacher_name': 'Prof. Marcus Brody',
                'attendance': '97%',
                'grade': 'A+',
                'equipment': 'PostgreSQL 16 clusters, Docker containers, pgAdmin workstations',
                'latest_update': 'ACID transactions, indexing, and trigger procedures benchmarked.',
            },
            {
                'lab_code': 'LAB-403',
                'name': 'Artificial Intelligence & Search Algorithms Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'AIML',
                'year': 2,
                'semester': 4,
                'day': 'Tuesday',
                'time_slot': '10:00 AM - 01:00 PM',
                'room': 'AI Innovation Hub - Lab 410',
                'teacher_name': 'Dr. Aman Gupta',
                'attendance': '96%',
                'grade': 'A+',
                'equipment': 'Python AI nodes, A* heuristic solvers, Minimax adversarial game testbeds',
                'latest_update': 'Constraint satisfaction and alpha-beta pruning trees benchmarked.',
            },
            {
                'lab_code': 'LAB-331',
                'name': 'Fluid Mechanics & Hydraulic Machinery Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'ME',
                'year': 2,
                'semester': 4,
                'day': 'Friday',
                'time_slot': '01:30 PM - 04:00 PM',
                'room': 'Thermal & Fluids Annex - Rig 02',
                'teacher_name': 'Dr. K. Srinivas',
                'attendance': '91%',
                'grade': 'A-',
                'equipment': 'Venturi flow meters, Pelton wheel impulse turbines, Reynolds apparatus',
                'latest_update': 'Bernoulli theorem and centrifugal pump characteristic curves analyzed.',
            },
            # Semester 5
            {
                'lab_code': 'LAB-503',
                'name': 'Big Data Analytics & Hadoop/Spark Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'DS',
                'year': 3,
                'semester': 5,
                'day': 'Monday',
                'time_slot': '10:00 AM - 01:00 PM',
                'room': 'High-Performance Cluster Lab 501',
                'teacher_name': 'Dr. Sarah Lin',
                'attendance': '95%',
                'grade': 'A',
                'equipment': 'Apache Hadoop 3.4 clusters, Apache Spark, PySpark compute nodes',
                'latest_update': 'MapReduce log parsing and Spark dataframe queries evaluated.',
            },
            {
                'lab_code': 'LAB-521',
                'name': 'Control Systems & MATLAB Simulation Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'EEE',
                'year': 3,
                'semester': 5,
                'day': 'Wednesday',
                'time_slot': '02:00 PM - 05:00 PM',
                'room': 'Electrical Simulation Bay 512',
                'teacher_name': 'Prof. A. K. Sundaram',
                'attendance': '93%',
                'grade': 'A',
                'equipment': 'MATLAB/Simulink licenses, Servomotor position control kits, Bode analyzer stations',
                'latest_update': 'Root locus and PID lag-lead compensator tuning completed.',
            },
            {
                'lab_code': 'LAB-321',
                'name': 'DC Machines & Electrical Transformers Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'EEE',
                'year': 3,
                'semester': 5,
                'day': 'Thursday',
                'time_slot': '09:30 AM - 12:30 PM',
                'room': 'Heavy Machinery Bay - Station 1',
                'teacher_name': 'Dr. T. Radhakrishnan',
                'attendance': '94%',
                'grade': 'A',
                'equipment': 'DC Shunt & Series Motor Dynamometers, 3-Phase Transformers, Autotransformer racks',
                'latest_update': 'Open-circuit and short-circuit test efficiency curves recorded.',
            },
            # Semester 6
            {
                'lab_code': 'LAB-601',
                'name': 'Compiler Design & Lex/Yacc Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'CSE',
                'year': 3,
                'semester': 6,
                'day': 'Monday',
                'time_slot': '09:00 AM - 12:00 PM',
                'room': 'Computing Block - Lab 305',
                'teacher_name': 'Prof. Marcus Vance',
                'attendance': '98%',
                'grade': 'O',
                'equipment': 'Flex & Bison suites, LLVM compiler toolchains, GDB assembler analyzers',
                'latest_update': 'Three-address intermediate code generation and syntax-directed translation ready.',
            },
            {
                'lab_code': 'LAB-641',
                'name': 'Structural Analysis & Concrete Testing Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'CIVIL',
                'year': 3,
                'semester': 6,
                'day': 'Tuesday',
                'time_slot': '01:30 PM - 04:30 PM',
                'room': 'Civil Materials Testing Annex',
                'teacher_name': 'Dr. P. N. Murthy',
                'attendance': '92%',
                'grade': 'A',
                'equipment': 'Universal Testing Machine (UTM 1000kN), Concrete compression testers, Slump cones',
                'latest_update': 'M30 mix design compressive strength and flexural tensile tests verified.',
            },
            {
                'lab_code': 'LAB-661',
                'name': 'Mechatronics & Industrial Automation Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'RA',
                'year': 3,
                'semester': 6,
                'day': 'Thursday',
                'time_slot': '10:00 AM - 01:00 PM',
                'room': 'Industrial Automation Bay 602',
                'teacher_name': 'Dr. K. Srinivas',
                'attendance': '94%',
                'grade': 'A',
                'equipment': 'Siemens S7-1200 PLCs, Festo electro-pneumatic training benches, SCADA consoles',
                'latest_update': 'Ladder logic automation for sequential sorting station deployed.',
            },
            # Semester 7
            {
                'lab_code': 'LAB-701',
                'name': 'Deep Learning & PyTorch Neural Networks Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'DS',
                'year': 4,
                'semester': 7,
                'day': 'Monday',
                'time_slot': '01:30 PM - 04:30 PM',
                'room': 'GPU AI Compute Rig 701',
                'teacher_name': 'Dr. Sarah Lin',
                'attendance': '99%',
                'grade': 'O',
                'equipment': 'NVIDIA RTX 4090 GPU nodes, PyTorch 2.4, CUDA 12.4, Weights & Biases telemetry',
                'latest_update': 'Vision Transformers (ViT) and ResNet fine-tuning benchmarks loaded.',
            },
            {
                'lab_code': 'LAB-731',
                'name': 'Heat Transfer & Thermal Engineering Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'ME',
                'year': 4,
                'semester': 7,
                'day': 'Wednesday',
                'time_slot': '09:30 AM - 12:30 PM',
                'room': 'Thermal Power Systems Rig 03',
                'teacher_name': 'Prof. V. K. Bansal',
                'attendance': '93%',
                'grade': 'A',
                'equipment': 'Shell and tube heat exchangers, Thermal pin-fin apparatus, Stefan-Boltzmann emissometers',
                'latest_update': 'Forced convection and heat transfer coefficient calibration completed.',
            },
            {
                'lab_code': 'LAB-751',
                'name': 'Embedded Systems & IoT Sensor Cloud Lab',
                'credits': 3,
                'course': 'B.Tech',
                'branch': 'ECM',
                'year': 4,
                'semester': 7,
                'day': 'Thursday',
                'time_slot': '02:00 PM - 05:00 PM',
                'room': 'IoT Gateway Testbed 704',
                'teacher_name': 'Dr. Aman Gupta',
                'attendance': '96%',
                'grade': 'O',
                'equipment': 'Raspberry Pi 5 clusters, ESP32 nodes, MQTT brokers, AWS IoT Greengrass rigs',
                'latest_update': 'End-to-end telemetry pipeline with TLS mutual authentication running.',
            },
            # Semester 8
            {
                'lab_code': 'LAB-801',
                'name': 'Major B.Tech Capstone Project & Prototype Lab',
                'credits': 6,
                'course': 'B.Tech',
                'branch': 'COMMON',
                'year': 4,
                'semester': 8,
                'day': 'Friday',
                'time_slot': '09:00 AM - 05:00 PM',
                'room': 'Incubation & Prototype Center - Bay 01',
                'teacher_name': 'Joint Faculty Evaluation Board',
                'attendance': '100%',
                'grade': 'O',
                'equipment': 'Prototype fabrication bays, Embedded telemetry stations, Cloud deployment racks',
                'latest_update': 'Phase 2 final hardware demonstrations and research paper review.',
            },
            {
                'lab_code': 'LAB-802',
                'name': 'VLSI System Design & Cadence Virtuoso Lab',
                'credits': 4,
                'course': 'B.Tech',
                'branch': 'ECE',
                'year': 4,
                'semester': 8,
                'day': 'Tuesday',
                'time_slot': '09:00 AM - 01:00 PM',
                'room': 'Microelectronics Cleanroom CAD Bay',
                'teacher_name': 'Dr. Aman Gupta',
                'attendance': '98%',
                'grade': 'O',
                'equipment': 'Cadence Virtuoso, Synopsys Design Compiler, 45nm CMOS PDKs',
                'latest_update': 'CMOS inverter layout, DRC/LVS verification, and post-layout timing verified.',
            },
        ]

        created_labs = {}
        for l in labs_data:
            lab = Lab.objects.create(**l)
            created_labs[l['lab_code']] = lab
        self.stdout.write(f"Created {len(created_labs)} B.Tech college laboratories.")

        # 4. Table: equipment_status (Comprehensive Matrix across ALL 25 laboratories)
        lab_equipments = {
            'LAB-101': [('Linux GCC 14.2 C Programming Stations', 'Working', '32/32 Stations', 'GDB debuggers and Valgrind suites online'), ('Clang C Formatter & Sanitizer Server', 'Working', '1 Server', 'AddressSanitizer and LeakSanitizer enabled')],
            'LAB-102': [('Dual-channel Regulated DC Power Supplies', 'Working', '20/20 Stations', '0-30V, 5A calibrated with overload protection'), ('Keysight Truevolt Digital Multimeters', 'Working', '20/20 Units', '6.5 digit precision DMM calibration certified')],
            'LAB-201': [('Python 3.13 High-Throughput Terminals', 'Working', '30/30 Stations', 'NumPy, Pandas, Matplotlib environments primed')],
            'LAB-204': [('Leica FlexLine TS07 Total Station Units', 'Working', '8/8 Units', 'Electronic distance measurement calibrated'), ('Digital Auto Levels & Aluminum Tripods', 'Working', '12/12 Rigs', 'Optical self-leveling compensators verified')],
            'LAB-261': [('6-DOF Articulated Robotic Manipulator Rigs', 'Working', '8/8 Rigs', 'Closed-loop servo feedback and PID tuned'), ('Ultrasonic & Solid-State LIDAR Sensors', 'Working', '16/16 Units', 'I2C and SPI bus telemetries operational')],
            'LAB-301': [('Linux C++23 High-Performance Nodes', 'Working', '32/32 Stations', 'GCC 14.2 & Clang 19 with Valgrind 3.23'), ('Automated Test Grader & Benchmarking Rack', 'Working', '1 Server', 'Dockerized test runner pool active')],
            'LAB-302': [('IntelliJ IDEA & OpenJDK 21 LTS Terminals', 'Working', '32/32 Terminals', 'Maven & Gradle local repository primed')],
            'LAB-303': [('Xilinx Vivado Basys 3 Artix-7 FPGA Boards', 'Working', '16/16 Benches', 'Bitstream programming cables tested'), ('Tektronix Mixed-Domain Oscilloscopes', 'Working', '16/16 Scopes', '4-channel 100MHz logic capture online')],
            'LAB-311': [('Keysight 100MHz Digital Storage Scopes', 'Working', '16/16 Benches', 'All probes calibrated to 10:1 ratio'), ('NI ELVIS III Prototyping Workstations', 'Working', '12/12 Stations', 'BJT and MOSFET frequency analyzers online')],
            'LAB-321': [('DC Shunt & Series Motor Dynamometers', 'Working', '10/10 Racks', 'Digital optical tachometers zeroed')],
            'LAB-331': [('Pelton Wheel Impulse Turbine Flow Rig', 'Working', '8/8 Stations', 'Pressure transducers zero-calibrated')],
            'LAB-351': [('ARM Cortex-M4 STM32 Nucleo Kits', 'Working', '24/24 Kits', 'J-Link debug probes and Keil uVision live')],
            'LAB-401': [('Linux Kernel 6.8 QEMU Debug Sandboxes', 'Working', '32/32 Nodes', 'Kernel module symbol tables loaded')],
            'LAB-402': [('PostgreSQL 16 Dedicated Query Sandboxes', 'Working', '30/30 Nodes', 'EXPLAIN ANALYZE visualizer modules primed')],
            'LAB-403': [('NVIDIA RTX 4090 GPU Deep Learning Rigs', 'Working', '8/8 Rigs', 'PyTorch 2.5 and CUDA 12.6 verified')],
            'LAB-503': [('Apache Spark 3.5 Distributed Cluster Nodes', 'Working', '12 Nodes', 'In-memory Resilient Distributed Datasets primed')],
            'LAB-521': [('Power Electronics Inverter & Rectifier Racks', 'Working', '12/12 Racks', 'IGBT gating circuits and protection relays calibrated')],
            'LAB-601': [('Automated QA Selenium Chrome Driver Grid', 'Working', '25/25 Nodes', 'Parallel end-to-end regression nodes live')],
            'LAB-641': [('Shimadzu 1000kN Universal Testing Machine', 'Working', '2 Machines', 'Extensometers certified for tensile tests')],
            'LAB-661': [('Industrial PLC & SCADA Simulation Racks', 'Working', '10/10 Benches', 'Siemens S7-1200 controllers online')],
            'LAB-701': [('Hadoop 3.3 Multi-Node Petabyte Cluster', 'Working', '10 Nodes', 'NameNode and DataNode daemons healthy')],
            'LAB-731': [('Haas 3-Axis CNC Milling & Lathe Centers', 'Working', '6/6 Stations', 'G-code path verification software online')],
            'LAB-751': [('IoT Gateway Rigs & ESP32 Sensor Nodes', 'Working', '20/20 Stations', 'MQTT TLS 1.3 brokers active')],
            'LAB-801': [('Dual-Extrusion 3D Printers & CO2 Laser Cutters', 'Working', '6/6 Stations', 'PLA/ABS filaments loaded and bed leveled')],
            'LAB-802': [('Cadence Virtuoso IC618 Cleanroom Terminals', 'Working', '15/15 Stations', '45nm CMOS PDKs and Spectre simulator ready')],
        }
        for code, items in lab_equipments.items():
            if code in created_labs:
                lab = created_labs[code]
                for name, st, count, note in items:
                    EquipmentStatus.objects.create(lab=lab, name=name, status=st, count_info=count, note=note)


        # 5. Table: lab_modules (Diverse file formats: .pdf, .py, .c, .sql, .ipynb, .jpeg, .v)
        modules_data = [
            (created_labs['LAB-301'], 'Lab Manual 01: Linked Lists & Dynamic Memory in C++', 'LAB301_Manual_01_Lists.pdf'),
            (created_labs['LAB-301'], 'Source Code 01: AVL Balanced Tree Rotations', 'avl_tree_rotations.cpp'),
            (created_labs['LAB-301'], 'Python Benchmark: Dijkstra Shortest Path Solver', 'dijkstra_benchmark.py'),
            (created_labs['LAB-302'], 'Lab Manual 01: Polymorphism, Interfaces & Generics', 'LAB302_Manual_01_OOP.pdf'),
            (created_labs['LAB-302'], 'Java Harness: Thread Synchronization & Concurrency', 'ThreadSyncRunner.java'),
            (created_labs['LAB-401'], 'Lab Manual 01: Linux Kernel Architecture & Syscalls', 'LAB401_Manual_Kernel.pdf'),
            (created_labs['LAB-401'], 'Kernel C Source: System Call Interception Hook', 'syscall_interceptor.c'),
            (created_labs['LAB-402'], 'Lab Manual 01: Relational Normalization & BCNF', 'LAB402_Manual_01_SQL.pdf'),
            (created_labs['LAB-402'], 'SQL Script: B-Tree Index Benchmark & Explain Analysis', 'benchmark_btree.sql'),
            (created_labs['LAB-402'], 'Jupyter Notebook: Query Performance & IO Cost Graphs', 'query_performance.ipynb'),
            (created_labs['LAB-402'], 'Architecture Diagram: PostgreSQL Cluster Sharding', 'cluster_sharding_topology.jpeg'),
            (created_labs['LAB-303'], 'Lab Manual 01: Verilog HDL Combinational Logic', 'LAB303_Manual_01_HDL.pdf'),
            (created_labs['LAB-303'], 'Verilog Core: 16-Bit Arithmetic Logic Unit', 'alu_16bit_core.v'),
            (created_labs['LAB-403'], 'Jupyter Notebook: PyTorch Backprop Gradient Descent', 'backprop_deep_learning.ipynb'),
        ]
        for lab, title, fname in modules_data:
            LabModule.objects.create(lab=lab, title=title, file_name=fname)

        # 6. Table: teacher_batches
        TeacherBatch.objects.create(
            batch_code='CSE-SEM4-B1',
            name='B.Tech CSE 2nd Year - DBMS & OS Practical',
            lab=created_labs['LAB-402'],
            day='Wednesday',
            time_slot='10:00 AM - 12:00 PM',
            room='Database Bay 401',
            students_count=32,
            attendance='96%',
            current_topic='ACID Isolation Levels & Query Optimization',
        )
        TeacherBatch.objects.create(
            batch_code='CSE-SEM3-B1',
            name='B.Tech CSE 2nd Year - DSA & Algorithms Cohort',
            lab=created_labs['LAB-301'],
            day='Monday',
            time_slot='09:00 AM - 11:30 AM',
            room='Computing Systems Lab 204',
            students_count=30,
            attendance='98%',
            current_topic='Balanced Search Trees (AVL & Red-Black)',
        )
        TeacherBatch.objects.create(
            batch_code='ECE-SEM3-B1',
            name='B.Tech ECE 2nd Year - Digital Verilog & EDC Cohort',
            lab=created_labs['LAB-303'],
            day='Tuesday',
            time_slot='09:00 AM - 11:30 AM',
            room='VLSI & Embedded Lab 202',
            students_count=28,
            attendance='94%',
            current_topic='16-bit ALU Verilog HDL Design & Basys 3 FPGA Verification',
        )

        # 7. Table: tasks (With Active Deadlines & Past Deadlines)
        task1 = Task.objects.create(
            title='PostgreSQL Index Optimization & Query Plan Benchmarking',
            category='Assignment',
            lab=created_labs['LAB-402'],
            due='Sep 20, 2026',
            description='Analyze query plans using EXPLAIN ANALYZE on a 500k-row relational schema with B-Tree and Hash indexes.',
            status='Pending',
        )
        task2 = Task.objects.create(
            title='AVL Tree Rotation & Balance Factor Verification',
            category='Assignment',
            lab=created_labs['LAB-301'],
            due='Sep 25, 2026',
            description='Implement LL, RR, LR, and RL rotations in C++23 with O(log n) height invariant checks.',
            status='Pending',
        )
        task3 = Task.objects.create(
            title='Kernel Module System Call Tracing & Strace Audit',
            category='Assignment',
            lab=created_labs['LAB-401'],
            due='Sep 01, 2026',
            description='Trace sys_read and sys_write invocations across multi-threaded worker pools in Linux kernel 6.8.',
            status='Closed / Deadline Expired',
        )

        # 8. Table: Live Workbenches (Clean & Ready for Physical Lab Sessions)
        workbenches_data = [
            ('WB-01', 'Database Bay 401', 'PostgreSQL Query Cluster Station #07', 'ready', 'Open'),
            ('WB-02', 'Computing Block - Lab 305', 'LLVM Compiler Terminal #14', 'ready', 'Open'),
            ('WB-03', 'VLSI & Embedded Lab 202', 'Xilinx Basys 3 FPGA Rig #03', 'ready', 'Open'),
            ('WB-04', 'Thermal & Fluids Annex - Rig 02', 'Pelton Wheel Turbine Rig #02', 'ready', 'Open'),
        ]
        for wid, lab_name, inst, st, usr in workbenches_data:
            LiveWorkbench.objects.create(
                workbench_id=wid,
                lab=lab_name,
                instrument=inst,
                status=st,
                user=usr,
            )

        self.stdout.write(self.style.SUCCESS('Successfully seeded institutional laboratories and admin user with zero demo data!'))
