-- ==============================================================================
-- LAB COMPANION - POSTGRESQL DATABASE SCHEMA (schema.sql)
-- Complete DDL Schema for PostgreSQL 12+ (Compatible with Supabase, Neon, AWS RDS)
-- Generated for Production Deployment
-- ==============================================================================

-- Enable UUID extension if needed in future
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ==============================================================================
-- 1. USERS TABLE (Students, Faculty, Institutional Administrators)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(20) NOT NULL CHECK (role IN ('student', 'teacher', 'admin')),
    user_id VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    dept VARCHAR(100),
    course VARCHAR(100) DEFAULT 'B.Tech - Computer Science & Engineering (CSE)',
    branch VARCHAR(50) DEFAULT 'CSE',
    year INTEGER DEFAULT 1,
    semester INTEGER DEFAULT 1,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(20),
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==============================================================================
-- 2. LABORATORIES TABLE (Curriculum Lab Catalog)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS labs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    credits INTEGER NOT NULL DEFAULT 2,
    course VARCHAR(100) DEFAULT 'B.Tech',
    branch VARCHAR(50) DEFAULT 'COMMON',
    year INTEGER DEFAULT 1,
    semester INTEGER DEFAULT 1,
    day VARCHAR(20),
    time_slot VARCHAR(100),
    room VARCHAR(100),
    teacher_name VARCHAR(100),
    attendance VARCHAR(20) DEFAULT '100%',
    grade VARCHAR(10) DEFAULT 'A',
    equipment TEXT,
    latest_update TEXT
);

-- ==============================================================================
-- 3. EQUIPMENT STATUS PER LABORATORY
-- ==============================================================================
CREATE TABLE IF NOT EXISTS equipment_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_id BIGINT NOT NULL REFERENCES labs(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL,
    count_info VARCHAR(100),
    note TEXT
);

-- ==============================================================================
-- 4. LAB MODULES / COURSEWARE & MANUALS
-- ==============================================================================
CREATE TABLE IF NOT EXISTS lab_modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lab_id BIGINT NOT NULL REFERENCES labs(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    title VARCHAR(150) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==============================================================================
-- 5. TEACHER SUPERVISED COHORT BATCHES
-- ==============================================================================
CREATE TABLE IF NOT EXISTS teacher_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    lab_id BIGINT NOT NULL REFERENCES labs(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    day VARCHAR(20),
    time_slot VARCHAR(100),
    room VARCHAR(100),
    students_count INTEGER DEFAULT 0,
    attendance VARCHAR(20) DEFAULT '100%',
    current_topic TEXT
);

-- ==============================================================================
-- 6. TASKS & LAB DELIVERABLES
-- ==============================================================================
CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    category VARCHAR(50) NOT NULL CHECK (category IN ('Assignment', 'Project', 'Module', 'Lab Material')),
    lab_id BIGINT NOT NULL REFERENCES labs(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    due VARCHAR(100),
    description TEXT,
    status VARCHAR(50) DEFAULT 'Pending' NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==============================================================================
-- 7. STUDENT REGISTERS & PERFORMANCE METRICS
-- ==============================================================================
CREATE TABLE IF NOT EXISTS student_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_code VARCHAR(50) NOT NULL UNIQUE,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    name VARCHAR(100) NOT NULL,
    lab_id BIGINT NOT NULL REFERENCES labs(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    dept VARCHAR(100),
    email VARCHAR(150),
    phone VARCHAR(20),
    attendance VARCHAR(20) DEFAULT '98%',
    grade VARCHAR(10) DEFAULT 'A+'
);

-- ==============================================================================
-- 8. STUDENT DELIVERABLE SUBMISSIONS
-- ==============================================================================
CREATE TABLE IF NOT EXISTS student_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED,
    student_name VARCHAR(100),
    task_id BIGINT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    lab_id BIGINT NOT NULL REFERENCES labs(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    category VARCHAR(50),
    file_name VARCHAR(255) NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status VARCHAR(50) DEFAULT 'Submitted' NOT NULL,
    grade VARCHAR(20),
    feedback TEXT
);

-- ==============================================================================
-- 9. LAB ATTENDANCE METRICS
-- ==============================================================================
CREATE TABLE IF NOT EXISTS lab_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    lab_id BIGINT NOT NULL REFERENCES labs(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    attended_classes INTEGER DEFAULT 0 NOT NULL,
    total_classes INTEGER DEFAULT 0 NOT NULL,
    attendance_percentage NUMERIC(5, 2),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT unique_student_lab_attendance UNIQUE (student_id, lab_id)
);

-- ==============================================================================
-- 10. FINAL LAB EVALUATION & GRADES
-- ==============================================================================
CREATE TABLE IF NOT EXISTS grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    lab_id BIGINT NOT NULL REFERENCES labs(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    grade VARCHAR(10) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT unique_student_lab_grade UNIQUE (student_id, lab_id)
);

-- ==============================================================================
-- 11. STUDENT ATTENDANCE CALENDAR SESSIONS (DAILY LOGS)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS student_attendance_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    lab_id BIGINT NOT NULL REFERENCES labs(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
    session_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('Present', 'Absent', 'Excused')),
    topic TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- ==============================================================================
-- 12. HARDWARE & EQUIPMENT ASSIGNMENTS
-- ==============================================================================
CREATE TABLE IF NOT EXISTS api_equipmentassignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "studentId" VARCHAR(50) NOT NULL,
    "studentName" VARCHAR(150) NOT NULL,
    "labId" VARCHAR(50) NOT NULL,
    equipment VARCHAR(200) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    "assignedOn" VARCHAR(100) NOT NULL
);

-- ==============================================================================
-- 13. REAL-TIME PHYSICAL LAB WORKBENCHES
-- ==============================================================================
CREATE TABLE IF NOT EXISTS api_liveworkbench (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workbench_id VARCHAR(50) NOT NULL UNIQUE,
    lab VARCHAR(150) NOT NULL,
    instrument VARCHAR(200) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ready',
    "user" VARCHAR(150) NOT NULL DEFAULT 'Open'
);

-- ==============================================================================
-- 14. STUDENT REGISTRATION & CLEARANCE REQUESTS (ADMIN GATING)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS student_registration_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    user_id VARCHAR(50) NOT NULL,
    password_hash TEXT NOT NULL,
    dept VARCHAR(100),
    course VARCHAR(100) DEFAULT 'B.Tech - Computer Science & Engineering (CSE)',
    branch VARCHAR(50) DEFAULT 'CSE',
    year INTEGER DEFAULT 1,
    semester INTEGER DEFAULT 1,
    phone VARCHAR(20),
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    rejection_reason TEXT
);

-- ==============================================================================
-- INDEXES FOR HIGH-PERFORMANCE RELATIONAL QUERIES & LOOKUPS
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_user_id ON users(user_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

CREATE INDEX IF NOT EXISTS idx_labs_code ON labs(lab_code);
CREATE INDEX IF NOT EXISTS idx_labs_branch_sem ON labs(branch, semester);

CREATE INDEX IF NOT EXISTS idx_equipment_status_lab ON equipment_status(lab_id);
CREATE INDEX IF NOT EXISTS idx_lab_modules_lab ON lab_modules(lab_id);
CREATE INDEX IF NOT EXISTS idx_teacher_batches_lab ON teacher_batches(lab_id);
CREATE INDEX IF NOT EXISTS idx_tasks_lab ON tasks(lab_id);

CREATE INDEX IF NOT EXISTS idx_student_records_user ON student_records(user_id);
CREATE INDEX IF NOT EXISTS idx_student_records_lab ON student_records(lab_id);
CREATE INDEX IF NOT EXISTS idx_student_records_code ON student_records(student_code);

CREATE INDEX IF NOT EXISTS idx_submissions_student ON student_submissions(student_id);
CREATE INDEX IF NOT EXISTS idx_submissions_task ON student_submissions(task_id);
CREATE INDEX IF NOT EXISTS idx_submissions_lab ON student_submissions(lab_id);

CREATE INDEX IF NOT EXISTS idx_attendance_student ON lab_attendance(student_id);
CREATE INDEX IF NOT EXISTS idx_attendance_lab ON lab_attendance(lab_id);

CREATE INDEX IF NOT EXISTS idx_grades_student ON grades(student_id);
CREATE INDEX IF NOT EXISTS idx_grades_lab ON grades(lab_id);

CREATE INDEX IF NOT EXISTS idx_sessions_student ON student_attendance_sessions(student_id);
CREATE INDEX IF NOT EXISTS idx_sessions_lab ON student_attendance_sessions(lab_id);
CREATE INDEX IF NOT EXISTS idx_sessions_date ON student_attendance_sessions(session_date);

CREATE INDEX IF NOT EXISTS idx_workbenches_id ON api_liveworkbench(workbench_id);
CREATE INDEX IF NOT EXISTS idx_registration_requests_status ON student_registration_requests(status);
CREATE INDEX IF NOT EXISTS idx_registration_requests_email ON student_registration_requests(email);
CREATE INDEX IF NOT EXISTS idx_registration_requests_user_id ON student_registration_requests(user_id);
